name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        source-url: https://nuget.pkg.github.com/scetrov/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./src

    - name: Pack NuGet Package
      run: dotnet pack --configuration Release --output ./nupkg
      working-directory: ./src/FrontierSharp.MudIndexer

    - name: Publish to GitHub Packages
      run: dotnet nuget push ./nupkg/*.nupkg --source "github.com/scetrov/index.json" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: ./src/FrontierSharp.MudIndexer
        
    - name: Publish to NuGet.org (Optional)
      run: dotnet nuget push ./nupkg/*.nupkg --source "nuget.org" --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      working-directory: ./src/FrontierSharp.MudIndexer
